### ISSUE TITLE
Set specific API Port for Xray and other Cores

### ISSUE THREAD

**Issue by APT-ZERO** [marzneshin/marznode#20]
Hello
Currently can't use Marznode on Docker with a network_mode other than 'host'
It will be possible if we become able to set an static api port for each core

**Comment by khodedawsh** [comment]
> Currently can't use Marznode on Docker with a network_mode other than 'host'

میتونی

**Comment by khodedawsh** [comment]
هیچکدوم. اصلا نیاز نیست پورتی مپ کنی. همون پورت های اینباند های خودت رو مپ کن
